# Generated by Django 4.0.5 on 2022-07-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0004_remove_problem_code_problem_inputfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='inputFile',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='outputFile',
        ),
        migrations.AddField(
            model_name='problem',
            name='code',
            field=models.CharField(default='code', max_length=1200),
        ),
    ]
