# Generated by Django 4.0.5 on 2022-07-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0006_remove_problem_code_problem_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=models.FileField(default='/Devesh/acc_out.txt', max_length=1000, upload_to='Devesh'),
        ),
    ]
